# Generated by Django 5.1.7 on 2025-10-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ratings',
            field=models.FloatField(default=0),
        ),
    ]
