# Generated by Django 5.1.7 on 2025-10-17 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviereview', '0002_review_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
